export const ROUTES = {
  HOME: "/",
  CASINO: "/casino",
  LIVE_CASINO: "/live-casino",
  SPORTS: "/sports",
  ESPORTS: "/esports",
  PROMOTIONS: "/promotions",
  ACTIVITY_CENTER: "/activity-center",
  MISSIONS: "/missions",
  NOTIFICATIONS: "/notifications",
  VIP_CLUB: "/vip-club",
  VIP_BENEFITS: "/vip-benefits",
  DEPOSIT: "/deposit",
  WITHDRAW: "/withdraw",
  MY_BETS: "/my-bets",
  TRANSACTIONS: "/transactions",
  SLOTS: "/slots",
  POKER: "/poker",
  FISHING: "/fishing",
  HOT: "/hot",
  NEW_GAMES: "/new-games",
  ELECTRONIC_GAMES: "/electronic-games",
  TABLE_GAMES: "/table-games",
  LIVE_ENTERTAINMENT: "/live-entertainment",
  FUTURES_TRADING: "/futures-trading",
  RECENT_GAMES: "/recent-games",
  SPORTSBOOK: "/sportsbook",
  USER_MANAGEMENT: "/user-management",
  ACCOUNT_SETTINGS: "/account-settings",
} as const

export type RouteKey = keyof typeof ROUTES
export type RouteValue = (typeof ROUTES)[RouteKey]
